'''
.. Created on Aug 9, 2012
.. codeauthor:: Robert Langlois <rl2528@columbia.edu>
'''
header_fields = (
    ('nx', 'int32'),
    ('ny', 'int32'),
    ('nz', 'int32'),
    ('mode', 'int32'),
    ('nxstart', 'int32'),
    ('nystart', 'int32'),
    ('nzstart', 'int32'),
    ('mx', 'int32'),
    ('my', 'int32'),
    ('mz', 'int32'),
    ('xlen', 'float32'),
    ('ylen', 'float32'),
    ('zlen', 'float32'),
    ('alpha', 'float32'),
    ('beta', 'float32'),
    ('gamma', 'float32'),
    ('mapc', 'int32'),
    ('mapr', 'int32'),
    ('maps', 'int32'),
    ('amin', 'float32'),
    ('amax', 'float32'),
    ('amean', 'float32'),
    ('ispg', 'int32'),
    ('nsymbt', 'int32'),
    ('extra', 'string', 100),
    ('xorigin', 'float32'),
    ('yorigin', 'float32'),
    ('zorigin', 'float32'),
    ('map', 'string', 4),
    ('byteorder', 'int32'),
    ('rms', 'float32'),
    ('nlabels', 'int32'),
    ('label0', 'string', 80),
    ('label1', 'string', 80),
    ('label2', 'string', 80),
    ('label3', 'string', 80),
    ('label4', 'string', 80),
    ('label5', 'string', 80),
    ('label6', 'string', 80),
    ('label7', 'string', 80),
    ('label8', 'string', 80),
    ('label9', 'string', 80),
)