# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/robertlanglois/workspace/arachnida/src/arachnid/core/gui/pyui/LeginonUI.ui'
#
# Created: Fri Dec  6 16:11:48 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from ..util.qt4_loader import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(396, 421)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginStackedWidget = QtGui.QStackedWidget(self.widget)
        self.loginStackedWidget.setObjectName("loginStackedWidget")
        self.welcomePage = QtGui.QWidget()
        self.welcomePage.setObjectName("welcomePage")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.welcomePage)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtGui.QWidget(self.welcomePage)
        self.widget_2.setObjectName("widget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.widget_2)
        self.formLayout_2.setContentsMargins(-1, -1, -1, 24)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.changeUserPushButton = QtGui.QPushButton(self.widget_2)
        self.changeUserPushButton.setObjectName("changeUserPushButton")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.changeUserPushButton)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.projectTableView = QtGui.QTableView(self.welcomePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.projectTableView.sizePolicy().hasHeightForWidth())
        self.projectTableView.setSizePolicy(sizePolicy)
        self.projectTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.projectTableView.setProperty("showDropIndicator", False)
        self.projectTableView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.projectTableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.projectTableView.setObjectName("projectTableView")
        self.verticalLayout_3.addWidget(self.projectTableView)
        self.loginStackedWidget.addWidget(self.welcomePage)
        self.loginPage = QtGui.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.gridLayout = QtGui.QGridLayout(self.loginPage)
        self.gridLayout.setContentsMargins(0, 0, 0, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.loginPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.leginonDBLineEdit = QtGui.QLineEdit(self.loginPage)
        self.leginonDBLineEdit.setObjectName("leginonDBLineEdit")
        self.gridLayout.addWidget(self.leginonDBLineEdit, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.loginPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.usernameLineEdit = QtGui.QLineEdit(self.loginPage)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout.addWidget(self.usernameLineEdit, 5, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.loginPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.projectDBLineEdit = QtGui.QLineEdit(self.loginPage)
        self.projectDBLineEdit.setObjectName("projectDBLineEdit")
        self.gridLayout.addWidget(self.projectDBLineEdit, 1, 1, 1, 1)
        self.passwordLineEdit = QtGui.QLineEdit(self.loginPage)
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.gridLayout.addWidget(self.passwordLineEdit, 6, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.loginPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 1, 1, 1)
        self.loginPushButton = QtGui.QPushButton(self.loginPage)
        self.loginPushButton.setObjectName("loginPushButton")
        self.gridLayout.addWidget(self.loginPushButton, 10, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(self.loginPage)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imagesPathLineEdit = QtGui.QLineEdit(self.widget_3)
        self.imagesPathLineEdit.setObjectName("imagesPathLineEdit")
        self.horizontalLayout.addWidget(self.imagesPathLineEdit)
        self.imagesPathPushButton = QtGui.QPushButton(self.widget_3)
        self.imagesPathPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mini/mini/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imagesPathPushButton.setIcon(icon)
        self.imagesPathPushButton.setObjectName("imagesPathPushButton")
        self.horizontalLayout.addWidget(self.imagesPathPushButton)
        self.gridLayout.addWidget(self.widget_3, 7, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.loginPage)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.widget_4 = QtGui.QWidget(self.loginPage)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.framesPathLineEdit = QtGui.QLineEdit(self.widget_4)
        self.framesPathLineEdit.setObjectName("framesPathLineEdit")
        self.horizontalLayout_2.addWidget(self.framesPathLineEdit)
        self.framesPathPushButton = QtGui.QPushButton(self.widget_4)
        self.framesPathPushButton.setText("")
        self.framesPathPushButton.setIcon(icon)
        self.framesPathPushButton.setObjectName("framesPathPushButton")
        self.horizontalLayout_2.addWidget(self.framesPathPushButton)
        self.gridLayout.addWidget(self.widget_4, 8, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.loginPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.loginStackedWidget.addWidget(self.loginPage)
        self.verticalLayout_2.addWidget(self.loginStackedWidget)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.loginStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Welcome", None, QtGui.QApplication.UnicodeUTF8))
        self.changeUserPushButton.setText(QtGui.QApplication.translate("Form", "Change User...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "URI Leginon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Project DB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.loginPushButton.setText(QtGui.QApplication.translate("Form", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Image path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Frame path", None, QtGui.QApplication.UnicodeUTF8))

from ..icons import icons_rc;icons_rc;
