# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/robertlanglois/workspace/arachnida/src/arachnid/core/gui/pyui/ProjectUI.ui'
#
# Created: Fri Jan 10 14:23:37 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from ..util.qt4_loader import QtCore, QtGui

class Ui_ProjectWizard(object):
    def setupUi(self, ProjectWizard):
        ProjectWizard.setObjectName("ProjectWizard")
        ProjectWizard.resize(719, 512)
        ProjectWizard.setWizardStyle(QtGui.QWizard.MacStyle)
        ProjectWizard.setOptions(QtGui.QWizard.IndependentPages|QtGui.QWizard.NoCancelButton|QtGui.QWizard.NoDefaultButton)
        self.introductionPage = QtGui.QWizardPage()
        self.introductionPage.setObjectName("introductionPage")
        self.gridLayout_2 = QtGui.QGridLayout(self.introductionPage)
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.introductionPage)
        self.label_4.setMinimumSize(QtCore.QSize(281, 0))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/icons/ColumbiaLogo.png"))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 0, 1, 2)
        self.screenShotCheckBox = QtGui.QCheckBox(self.introductionPage)
        self.screenShotCheckBox.setObjectName("screenShotCheckBox")
        self.gridLayout_2.addWidget(self.screenShotCheckBox, 9, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.introductionPage)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 241, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 113, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 151, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 241, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 241, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 113, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 151, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 241, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 113, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 241, 222))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 113, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 151, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 113, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 113, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 227, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_14.setPalette(palette)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setStyleSheet("padding-left: 3;\n"
"padding-top: 3;\n"
"\n"
"")
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 0, 2, 2)
        self.widget_5 = QtGui.QWidget(self.introductionPage)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtGui.QLabel(self.widget_5)
        self.label_2.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/icons/FrankLab_logo081511.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.label_5 = QtGui.QLabel(self.widget_5)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/icons/HHMIlogo.png"))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.gridLayout_2.addWidget(self.widget_5, 5, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.introductionPage)
        self.label_7.setMaximumSize(QtCore.QSize(110, 110))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icons/icons/220px-NIH_Master_Logo_Vertical_2Color.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 1, 1, 1)
        ProjectWizard.addPage(self.introductionPage)
        self.settingsQuestionPage = QtGui.QWizardPage()
        self.settingsQuestionPage.setObjectName("settingsQuestionPage")
        self.verticalLayout = QtGui.QVBoxLayout(self.settingsQuestionPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtGui.QWidget(self.settingsQuestionPage)
        self.widget_2.setObjectName("widget_2")
        self.formLayout_3 = QtGui.QFormLayout(self.widget_2)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.yesLeginonPushButton = QtGui.QPushButton(self.widget_2)
        self.yesLeginonPushButton.setMinimumSize(QtCore.QSize(250, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mini/mini/accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yesLeginonPushButton.setIcon(icon)
        self.yesLeginonPushButton.setCheckable(True)
        self.yesLeginonPushButton.setFlat(False)
        self.yesLeginonPushButton.setObjectName("yesLeginonPushButton")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.yesLeginonPushButton)
        self.noLeginonPushButton = QtGui.QPushButton(self.widget_2)
        self.noLeginonPushButton.setMinimumSize(QtCore.QSize(250, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/mini/mini/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.noLeginonPushButton.setIcon(icon1)
        self.noLeginonPushButton.setCheckable(True)
        self.noLeginonPushButton.setFlat(False)
        self.noLeginonPushButton.setObjectName("noLeginonPushButton")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.noLeginonPushButton)
        self.selectLeginonInformationToolButton = QtGui.QToolButton(self.widget_2)
        self.selectLeginonInformationToolButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/mini/mini/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectLeginonInformationToolButton.setIcon(icon2)
        self.selectLeginonInformationToolButton.setCheckable(False)
        self.selectLeginonInformationToolButton.setObjectName("selectLeginonInformationToolButton")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.selectLeginonInformationToolButton)
        self.verticalLayout.addWidget(self.widget_2)
        self.selectLeginonInformationLabel = QtGui.QLabel(self.settingsQuestionPage)
        self.selectLeginonInformationLabel.setWordWrap(True)
        self.selectLeginonInformationLabel.setObjectName("selectLeginonInformationLabel")
        self.verticalLayout.addWidget(self.selectLeginonInformationLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        ProjectWizard.addPage(self.settingsQuestionPage)
        self.leginonDBPage = QtGui.QWizardPage()
        self.leginonDBPage.setObjectName("leginonDBPage")
        self.leginonDBLayout = QtGui.QVBoxLayout(self.leginonDBPage)
        self.leginonDBLayout.setObjectName("leginonDBLayout")
        ProjectWizard.addPage(self.leginonDBPage)
        self.manualSettingsPage = QtGui.QWizardPage()
        self.manualSettingsPage.setObjectName("manualSettingsPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.manualSettingsPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(self.manualSettingsPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_6 = QtGui.QWidget(self.groupBox_2)
        self.widget_6.setObjectName("widget_6")
        self.formLayout_4 = QtGui.QFormLayout(self.widget_6)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.widget = QtGui.QWidget(self.widget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.micrographComboBox = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.micrographComboBox.sizePolicy().hasHeightForWidth())
        self.micrographComboBox.setSizePolicy(sizePolicy)
        self.micrographComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.micrographComboBox.setEditable(True)
        self.micrographComboBox.setObjectName("micrographComboBox")
        self.horizontalLayout.addWidget(self.micrographComboBox)
        self.micrographFileToolButton = QtGui.QToolButton(self.widget)
        self.micrographFileToolButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/mini/mini/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.micrographFileToolButton.setIcon(icon3)
        self.micrographFileToolButton.setObjectName("micrographFileToolButton")
        self.horizontalLayout.addWidget(self.micrographFileToolButton)
        self.openMoreFilesToolButton = QtGui.QToolButton(self.widget)
        self.openMoreFilesToolButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/mini/mini/folder_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openMoreFilesToolButton.setIcon(icon4)
        self.openMoreFilesToolButton.setObjectName("openMoreFilesToolButton")
        self.horizontalLayout.addWidget(self.openMoreFilesToolButton)
        self.displayImagesToolButton = QtGui.QToolButton(self.widget)
        self.displayImagesToolButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/mini/mini/images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.displayImagesToolButton.setIcon(icon5)
        self.displayImagesToolButton.setObjectName("displayImagesToolButton")
        self.horizontalLayout.addWidget(self.displayImagesToolButton)
        self.micrographInformationToolButton = QtGui.QToolButton(self.widget)
        self.micrographInformationToolButton.setText("")
        self.micrographInformationToolButton.setIcon(icon2)
        self.micrographInformationToolButton.setObjectName("micrographInformationToolButton")
        self.horizontalLayout.addWidget(self.micrographInformationToolButton)
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.widget)
        self.label_3 = QtGui.QLabel(self.widget_6)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_6 = QtGui.QLabel(self.widget_6)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.widget_3 = QtGui.QWidget(self.widget_6)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gainFileComboBox = QtGui.QComboBox(self.widget_3)
        self.gainFileComboBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainFileComboBox.sizePolicy().hasHeightForWidth())
        self.gainFileComboBox.setSizePolicy(sizePolicy)
        self.gainFileComboBox.setEditable(True)
        self.gainFileComboBox.setObjectName("gainFileComboBox")
        self.horizontalLayout_3.addWidget(self.gainFileComboBox)
        self.gainFilePushButton = QtGui.QPushButton(self.widget_3)
        self.gainFilePushButton.setEnabled(False)
        self.gainFilePushButton.setText("")
        self.gainFilePushButton.setIcon(icon3)
        self.gainFilePushButton.setAutoDefault(False)
        self.gainFilePushButton.setFlat(True)
        self.gainFilePushButton.setObjectName("gainFilePushButton")
        self.horizontalLayout_3.addWidget(self.gainFilePushButton)
        self.gainInformationToolButton = QtGui.QToolButton(self.widget_3)
        self.gainInformationToolButton.setText("")
        self.gainInformationToolButton.setIcon(icon2)
        self.gainInformationToolButton.setObjectName("gainInformationToolButton")
        self.horizontalLayout_3.addWidget(self.gainInformationToolButton)
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.widget_3)
        self.invertCheckBox = QtGui.QCheckBox(self.widget_6)
        self.invertCheckBox.setChecked(True)
        self.invertCheckBox.setObjectName("invertCheckBox")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.invertCheckBox)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.imageStatTableView = QtGui.QTableView(self.groupBox_2)
        self.imageStatTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.imageStatTableView.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.imageStatTableView.setObjectName("imageStatTableView")
        self.verticalLayout_4.addWidget(self.imageStatTableView)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.manualSettingsPage)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_10.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_9 = QtGui.QWidget(self.groupBox)
        self.widget_9.setObjectName("widget_9")
        self.formLayout_2 = QtGui.QFormLayout(self.widget_9)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtGui.QLabel(self.widget_9)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.pixelSizeDoubleSpinBox = QtGui.QDoubleSpinBox(self.widget_9)
        self.pixelSizeDoubleSpinBox.setObjectName("pixelSizeDoubleSpinBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pixelSizeDoubleSpinBox)
        self.label_10 = QtGui.QLabel(self.widget_9)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.voltageDoubleSpinBox = QtGui.QDoubleSpinBox(self.widget_9)
        self.voltageDoubleSpinBox.setMaximum(5000.0)
        self.voltageDoubleSpinBox.setObjectName("voltageDoubleSpinBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.voltageDoubleSpinBox)
        self.label_11 = QtGui.QLabel(self.widget_9)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.csDoubleSpinBox = QtGui.QDoubleSpinBox(self.widget_9)
        self.csDoubleSpinBox.setObjectName("csDoubleSpinBox")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.csDoubleSpinBox)
        self.horizontalLayout_10.addWidget(self.widget_9)
        self.importMessageLabel = QtGui.QLabel(self.groupBox)
        self.importMessageLabel.setWordWrap(True)
        self.importMessageLabel.setObjectName("importMessageLabel")
        self.horizontalLayout_10.addWidget(self.importMessageLabel)
        self.verticalLayout_2.addWidget(self.groupBox)
        ProjectWizard.addPage(self.manualSettingsPage)
        self.referenceQuestionPage = QtGui.QWizardPage()
        self.referenceQuestionPage.setObjectName("referenceQuestionPage")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.referenceQuestionPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtGui.QWidget(self.referenceQuestionPage)
        self.widget_4.setObjectName("widget_4")
        self.formLayout_5 = QtGui.QFormLayout(self.widget_4)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.yesReferencePushButton = QtGui.QPushButton(self.widget_4)
        self.yesReferencePushButton.setMinimumSize(QtCore.QSize(250, 50))
        self.yesReferencePushButton.setIcon(icon)
        self.yesReferencePushButton.setCheckable(True)
        self.yesReferencePushButton.setFlat(False)
        self.yesReferencePushButton.setObjectName("yesReferencePushButton")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.yesReferencePushButton)
        self.noReferencePushButton = QtGui.QPushButton(self.widget_4)
        self.noReferencePushButton.setMinimumSize(QtCore.QSize(250, 50))
        self.noReferencePushButton.setIcon(icon1)
        self.noReferencePushButton.setCheckable(True)
        self.noReferencePushButton.setFlat(False)
        self.noReferencePushButton.setObjectName("noReferencePushButton")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.noReferencePushButton)
        self.selectReferenceInformationToolButton = QtGui.QToolButton(self.widget_4)
        self.selectReferenceInformationToolButton.setText("")
        self.selectReferenceInformationToolButton.setIcon(icon2)
        self.selectReferenceInformationToolButton.setCheckable(False)
        self.selectReferenceInformationToolButton.setObjectName("selectReferenceInformationToolButton")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.selectReferenceInformationToolButton)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.selectReferenceInformationLabel = QtGui.QLabel(self.referenceQuestionPage)
        self.selectReferenceInformationLabel.setWordWrap(True)
        self.selectReferenceInformationLabel.setObjectName("selectReferenceInformationLabel")
        self.verticalLayout_3.addWidget(self.selectReferenceInformationLabel)
        ProjectWizard.addPage(self.referenceQuestionPage)
        self.referencePage = QtGui.QWizardPage()
        self.referencePage.setObjectName("referencePage")
        self.referenceLayout = QtGui.QHBoxLayout(self.referencePage)
        self.referenceLayout.setObjectName("referenceLayout")
        ProjectWizard.addPage(self.referencePage)
        self.additionalSettingsPage = QtGui.QWizardPage()
        self.additionalSettingsPage.setObjectName("additionalSettingsPage")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.additionalSettingsPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtGui.QGroupBox(self.additionalSettingsPage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.particleDiameterStackedWidget = QtGui.QStackedWidget(self.groupBox_4)
        self.particleDiameterStackedWidget.setObjectName("particleDiameterStackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.particleSizeDoubleSpinBox = QtGui.QDoubleSpinBox(self.page)
        self.particleSizeDoubleSpinBox.setMaximum(10000.0)
        self.particleSizeDoubleSpinBox.setObjectName("particleSizeDoubleSpinBox")
        self.horizontalLayout_2.addWidget(self.particleSizeDoubleSpinBox)
        self.particleDiameterStackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.particleSizeSpinBox = QtGui.QSpinBox(self.page_2)
        self.particleSizeSpinBox.setMaximum(10000)
        self.particleSizeSpinBox.setObjectName("particleSizeSpinBox")
        self.horizontalLayout_4.addWidget(self.particleSizeSpinBox)
        self.particleDiameterStackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.particleDiameterStackedWidget, 0, 1, 1, 1)
        self.particleSizeUnitComboBox = QtGui.QComboBox(self.groupBox_4)
        self.particleSizeUnitComboBox.setObjectName("particleSizeUnitComboBox")
        self.particleSizeUnitComboBox.addItem("")
        self.particleSizeUnitComboBox.addItem("")
        self.gridLayout.addWidget(self.particleSizeUnitComboBox, 0, 2, 1, 1)
        self.windowSizeUnitComboBox = QtGui.QComboBox(self.groupBox_4)
        self.windowSizeUnitComboBox.setObjectName("windowSizeUnitComboBox")
        self.windowSizeUnitComboBox.addItem("")
        self.windowSizeUnitComboBox.addItem("")
        self.gridLayout.addWidget(self.windowSizeUnitComboBox, 1, 2, 1, 1)
        self.windowSizeStackedWidget = QtGui.QStackedWidget(self.groupBox_4)
        self.windowSizeStackedWidget.setObjectName("windowSizeStackedWidget")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.page_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.windowSizeDoubleSpinBox = QtGui.QDoubleSpinBox(self.page_3)
        self.windowSizeDoubleSpinBox.setMaximum(10000.0)
        self.windowSizeDoubleSpinBox.setObjectName("windowSizeDoubleSpinBox")
        self.horizontalLayout_5.addWidget(self.windowSizeDoubleSpinBox)
        self.windowSizeStackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.page_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.windowSizeSpinBox = QtGui.QSpinBox(self.page_4)
        self.windowSizeSpinBox.setMaximum(10000)
        self.windowSizeSpinBox.setObjectName("windowSizeSpinBox")
        self.horizontalLayout_6.addWidget(self.windowSizeSpinBox)
        self.windowSizeStackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.windowSizeStackedWidget, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.maskDiameterStackedWidget = QtGui.QStackedWidget(self.groupBox_4)
        self.maskDiameterStackedWidget.setObjectName("maskDiameterStackedWidget")
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.page_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.maskDiameterDoubleSpinBox = QtGui.QDoubleSpinBox(self.page_5)
        self.maskDiameterDoubleSpinBox.setMaximum(10000.0)
        self.maskDiameterDoubleSpinBox.setObjectName("maskDiameterDoubleSpinBox")
        self.horizontalLayout_7.addWidget(self.maskDiameterDoubleSpinBox)
        self.maskDiameterStackedWidget.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.page_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.maskDiameterSpinBox = QtGui.QSpinBox(self.page_6)
        self.maskDiameterSpinBox.setMaximum(10000)
        self.maskDiameterSpinBox.setObjectName("maskDiameterSpinBox")
        self.horizontalLayout_8.addWidget(self.maskDiameterSpinBox)
        self.maskDiameterStackedWidget.addWidget(self.page_6)
        self.gridLayout.addWidget(self.maskDiameterStackedWidget, 2, 1, 1, 1)
        self.maskDiameterUnitComboBox = QtGui.QComboBox(self.groupBox_4)
        self.maskDiameterUnitComboBox.setObjectName("maskDiameterUnitComboBox")
        self.maskDiameterUnitComboBox.addItem("")
        self.maskDiameterUnitComboBox.addItem("")
        self.gridLayout.addWidget(self.maskDiameterUnitComboBox, 2, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 1, 1, 1)
        self.dimensionInformationToolButton = QtGui.QToolButton(self.groupBox_4)
        self.dimensionInformationToolButton.setText("")
        self.dimensionInformationToolButton.setIcon(icon2)
        self.dimensionInformationToolButton.setObjectName("dimensionInformationToolButton")
        self.gridLayout.addWidget(self.dimensionInformationToolButton, 0, 3, 1, 1)
        self.sampleShapeComboBox = QtGui.QComboBox(self.groupBox_4)
        self.sampleShapeComboBox.setObjectName("sampleShapeComboBox")
        self.sampleShapeComboBox.addItem("")
        self.sampleShapeComboBox.addItem("")
        self.gridLayout.addWidget(self.sampleShapeComboBox, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.sampleShapeInfoToolButton = QtGui.QToolButton(self.groupBox_4)
        self.sampleShapeInfoToolButton.setText("")
        self.sampleShapeInfoToolButton.setIcon(icon2)
        self.sampleShapeInfoToolButton.setObjectName("sampleShapeInfoToolButton")
        self.gridLayout.addWidget(self.sampleShapeInfoToolButton, 3, 3, 1, 1)
        self.sampleDensityComboBox = QtGui.QComboBox(self.groupBox_4)
        self.sampleDensityComboBox.setObjectName("sampleDensityComboBox")
        self.sampleDensityComboBox.addItem("")
        self.sampleDensityComboBox.addItem("")
        self.sampleDensityComboBox.addItem("")
        self.gridLayout.addWidget(self.sampleDensityComboBox, 4, 1, 1, 1)
        self.sampleDensityInfoToolButton = QtGui.QToolButton(self.groupBox_4)
        self.sampleDensityInfoToolButton.setIcon(icon2)
        self.sampleDensityInfoToolButton.setObjectName("sampleDensityInfoToolButton")
        self.gridLayout.addWidget(self.sampleDensityInfoToolButton, 4, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.additionalSettingsPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.workerCountSpinBox = QtGui.QSpinBox(self.groupBox_3)
        self.workerCountSpinBox.setMaximum(10000)
        self.workerCountSpinBox.setProperty("value", 1)
        self.workerCountSpinBox.setObjectName("workerCountSpinBox")
        self.gridLayout_3.addWidget(self.workerCountSpinBox, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 1, 0, 1, 1)
        self.threadCountSpinBox = QtGui.QSpinBox(self.groupBox_3)
        self.threadCountSpinBox.setMaximum(10000)
        self.threadCountSpinBox.setProperty("value", 1)
        self.threadCountSpinBox.setObjectName("threadCountSpinBox")
        self.gridLayout_3.addWidget(self.threadCountSpinBox, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 3, 1, 1)
        self.parallelInformationToolButton = QtGui.QToolButton(self.groupBox_3)
        self.parallelInformationToolButton.setText("")
        self.parallelInformationToolButton.setIcon(icon2)
        self.parallelInformationToolButton.setObjectName("parallelInformationToolButton")
        self.gridLayout_3.addWidget(self.parallelInformationToolButton, 0, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.additionalSettingsPage)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.enableStderrCheckBox = QtGui.QCheckBox(self.groupBox_5)
        self.enableStderrCheckBox.setText("")
        self.enableStderrCheckBox.setObjectName("enableStderrCheckBox")
        self.gridLayout_4.addWidget(self.enableStderrCheckBox, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 3, 1, 1)
        self.logInformationToolButton = QtGui.QToolButton(self.groupBox_5)
        self.logInformationToolButton.setText("")
        self.logInformationToolButton.setIcon(icon2)
        self.logInformationToolButton.setObjectName("logInformationToolButton")
        self.gridLayout_4.addWidget(self.logInformationToolButton, 0, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        ProjectWizard.addPage(self.additionalSettingsPage)
        self.fineTunePage = QtGui.QWizardPage()
        self.fineTunePage.setSubTitle("")
        self.fineTunePage.setObjectName("fineTunePage")
        self.settingsHorizontalLayout = QtGui.QHBoxLayout(self.fineTunePage)
        self.settingsHorizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.settingsHorizontalLayout.setObjectName("settingsHorizontalLayout")
        self.widget_8 = QtGui.QWidget(self.fineTunePage)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.workflowListView = QtGui.QListView(self.widget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workflowListView.sizePolicy().hasHeightForWidth())
        self.workflowListView.setSizePolicy(sizePolicy)
        self.workflowListView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.workflowListView.setObjectName("workflowListView")
        self.verticalLayout_8.addWidget(self.workflowListView)
        self.widget_7 = QtGui.QWidget(self.widget_8)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.documentationURLToolButton = QtGui.QToolButton(self.widget_7)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/mini/mini/world_link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.documentationURLToolButton.setIcon(icon6)
        self.documentationURLToolButton.setObjectName("documentationURLToolButton")
        self.horizontalLayout_9.addWidget(self.documentationURLToolButton)
        self.settingsInformatToolButton = QtGui.QToolButton(self.widget_7)
        self.settingsInformatToolButton.setText("")
        self.settingsInformatToolButton.setIcon(icon2)
        self.settingsInformatToolButton.setObjectName("settingsInformatToolButton")
        self.horizontalLayout_9.addWidget(self.settingsInformatToolButton)
        self.verticalLayout_8.addWidget(self.widget_7)
        self.settingsHorizontalLayout.addWidget(self.widget_8)
        ProjectWizard.addPage(self.fineTunePage)
        self.monitorPage = QtGui.QWizardPage()
        self.monitorPage.setObjectName("monitorPage")
        self.monitorLayout = QtGui.QVBoxLayout(self.monitorPage)
        self.monitorLayout.setContentsMargins(0, 0, 0, 0)
        self.monitorLayout.setObjectName("monitorLayout")
        ProjectWizard.addPage(self.monitorPage)
        self.label_9.setBuddy(self.particleSizeDoubleSpinBox)
        self.label_21.setBuddy(self.windowSizeDoubleSpinBox)
        self.label.setBuddy(self.maskDiameterDoubleSpinBox)
        self.label_19.setBuddy(self.workerCountSpinBox)
        self.label_20.setBuddy(self.threadCountSpinBox)
        self.label_12.setBuddy(self.enableStderrCheckBox)

        self.retranslateUi(ProjectWizard)
        self.particleDiameterStackedWidget.setCurrentIndex(0)
        self.windowSizeStackedWidget.setCurrentIndex(0)
        self.maskDiameterStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ProjectWizard)

    def retranslateUi(self, ProjectWizard):
        ProjectWizard.setWindowTitle(QtGui.QApplication.translate("ProjectWizard", "Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.introductionPage.setTitle(QtGui.QApplication.translate("ProjectWizard", "Welcome to Arachnid", None, QtGui.QApplication.UnicodeUTF8))
        self.introductionPage.setSubTitle(QtGui.QApplication.translate("ProjectWizard", "This wizard will take you through setting up a workflow to process data collected by electron microscopy", None, QtGui.QApplication.UnicodeUTF8))
        self.screenShotCheckBox.setText(QtGui.QApplication.translate("ProjectWizard", "Take screen shots", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">Credits</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#000000;\">Robert Langlois</span> (Lead developer), <span style=\" font-weight:600;\">Nam Ho</span> (Graphics and Ergonomics), <span style=\" font-weight:600;\">Melissa Thomas </span>(Graphics), <span style=\" font-weight:600;\">Johnathan Ginsburg</span> (pySPIDER), <span style=\" font-weight:600;\">Jordan T. Ash</span> (ViCer), <span style=\" font-weight:600;\">Ryan H. Smith</span> (Movie-mode Alignment) and <span style=\" font-weight:600;\">Hstau Liao</span> (Movie-mode Alignment)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsQuestionPage.setTitle(QtGui.QApplication.translate("ProjectWizard", "Leginon Settings Import", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsQuestionPage.setSubTitle(QtGui.QApplication.translate("ProjectWizard", "Would you like to import your experimental settings from a Leginon database?", None, QtGui.QApplication.UnicodeUTF8))
        self.yesLeginonPushButton.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/accept.png\" /> <span style=\" font-weight:600; text-decoration: underline;\">YES</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you click Yes, then the program will attempt to connect to the Leginon Database and retrieve your most recent sessions. You will be able to select multiple sessions and this information will be used to</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">fill the next page: Manual Settings.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.yesLeginonPushButton.setText(QtGui.QApplication.translate("ProjectWizard", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.noLeginonPushButton.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/cancel.png\" /> <span style=\" font-weight:600; text-decoration: underline;\">NO</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you click No, then you will be brought to the Manual Settings page where you will be prompted to enter information concerning the data you wish to process manually.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.noLeginonPushButton.setText(QtGui.QApplication.translate("ProjectWizard", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.selectLeginonInformationLabel.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/cancel.png\" /> <span style=\" font-weight:600; text-decoration: underline;\">NO</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you click No, then you will be brought to the Manual Settings page where you will be prompted to enter information concerning the data you wish to process manually.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.selectLeginonInformationLabel.setText(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/accept.png\" /> <span style=\" font-weight:600; text-decoration: underline;\">YES</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you click Yes, then the program will attempt to connect to the Leginon Database and retrieve your most recent sessions. You will be able to select multiple sessions and this information will be used to</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">fill the next page: Manual Settings.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/cancel.png\" /> <span style=\" font-weight:600; text-decoration: underline;\">NO</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you click No, then you will be brought to the Manual Settings page where you will be prompted to enter information concerning the data you wish to process manually.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.leginonDBPage.setTitle(QtGui.QApplication.translate("ProjectWizard", "Leginon Import", None, QtGui.QApplication.UnicodeUTF8))
        self.manualSettingsPage.setTitle(QtGui.QApplication.translate("ProjectWizard", "Manual Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ProjectWizard", "Images", None, QtGui.QApplication.UnicodeUTF8))
        self.micrographComboBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select micrograph image (or stack) files for processing.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/bullet_black.png\" />Writing the filename with optional regular expression in the text box</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/bullet_black.png\" />Selecting files using the system file chooser  <img src=\":/mini/mini/folder.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/bullet_black.png\" />Add additional files using the system file chooser <img src=\":/mini/mini/folder_add.png\" /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The files will be listed in the drop down list <img src=\":/mini/mini/bullet_arrow_down.png\" />.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The files can be viewed using <img src=\":/mini/mini/images.png\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.micrographFileToolButton.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Open list of files", None, QtGui.QApplication.UnicodeUTF8))
        self.openMoreFilesToolButton.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Add more files to list", None, QtGui.QApplication.UnicodeUTF8))
        self.displayImagesToolButton.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Display images", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ProjectWizard", "Micrographs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ProjectWizard", "Gain image", None, QtGui.QApplication.UnicodeUTF8))
        self.gainFileComboBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">File path for the gain normalization image</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/asterisk_orange.png\" /> Multiple files are currently only supported from Leginon input</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/asterisk_orange.png\" /> This file is only necessary for frames collected in movie mode</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.invertCheckBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Do the micrographs require contrast inversion?</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/exclamation.png\" /> This is should only be unchecked if you performed contrast inversion while scanning film micrographs.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.invertCheckBox.setText(QtGui.QApplication.translate("ProjectWizard", "Invert Contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ProjectWizard", "Microscope Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ProjectWizard", "Pixel Size (1/A)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ProjectWizard", "Voltage (kV)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("ProjectWizard", "CS (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.importMessageLabel.setText(QtGui.QApplication.translate("ProjectWizard", "These settings were imported from Leginon.\n"
"\n"
"You may change them, however, this is not advisable.", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceQuestionPage.setTitle(QtGui.QApplication.translate("ProjectWizard", "Reference Preprocessing", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceQuestionPage.setSubTitle(QtGui.QApplication.translate("ProjectWizard", "Would you like to select a raw map to be transformed into a reference?", None, QtGui.QApplication.UnicodeUTF8))
        self.yesReferencePushButton.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/accept.png\" /> <span style=\" font-weight:600; text-decoration: underline;\">YES</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you click Yes, then you will be asked to either select a structure from the EMDB or a local file.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.yesReferencePushButton.setText(QtGui.QApplication.translate("ProjectWizard", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.noReferencePushButton.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/cancel.png\" /> <span style=\" font-weight:600; text-decoration: underline;\">NO</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you click No, then you will skip this step. Generally, you will do this if you already have a reference from a previous experiment or are generating a reference <span style=\" font-style:italic;\">ab initio</span>.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.noReferencePushButton.setText(QtGui.QApplication.translate("ProjectWizard", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.selectReferenceInformationLabel.setText(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/accept.png\" /> <span style=\" font-weight:600; text-decoration: underline;\">YES</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you click Yes, then you will be asked to either select a structure from the EMDB or a local file.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/cancel.png\" /> <span style=\" font-weight:600; text-decoration: underline;\">NO</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you click No, then you will skip this step. Generally, you will do this if you already have a reference from a previous experiment or are generating a reference <span style=\" font-style:italic;\">ab initio</span>.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.referencePage.setTitle(QtGui.QApplication.translate("ProjectWizard", "Reference Map", None, QtGui.QApplication.UnicodeUTF8))
        self.additionalSettingsPage.setTitle(QtGui.QApplication.translate("ProjectWizard", "Additional Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ProjectWizard", "Data dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ProjectWizard", "Particle Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.particleSizeDoubleSpinBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The diameter of the particle is used for particle selection. Also changing this value updates both the Window Width (1.4*Particle Diameter) and the Mask Diameter (1.2*Particle Diameter). </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/asterisk_orange.png\" />The mask diameter must match the Particle Diameter in angular refinement (e.g. Relion).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.particleSizeUnitComboBox.setItemText(0, QtGui.QApplication.translate("ProjectWizard", "Å", None, QtGui.QApplication.UnicodeUTF8))
        self.particleSizeUnitComboBox.setItemText(1, QtGui.QApplication.translate("ProjectWizard", "Px", None, QtGui.QApplication.UnicodeUTF8))
        self.windowSizeUnitComboBox.setItemText(0, QtGui.QApplication.translate("ProjectWizard", "Å", None, QtGui.QApplication.UnicodeUTF8))
        self.windowSizeUnitComboBox.setItemText(1, QtGui.QApplication.translate("ProjectWizard", "Px", None, QtGui.QApplication.UnicodeUTF8))
        self.windowSizeDoubleSpinBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Width of the window containing a particle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Window width in pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("ProjectWizard", "Window Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ProjectWizard", "Mask Diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.maskDiameterDoubleSpinBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Diameter of mask used in refinement (e.g. Relion) ensures the normalization matches the mask", None, QtGui.QApplication.UnicodeUTF8))
        self.maskDiameterUnitComboBox.setItemText(0, QtGui.QApplication.translate("ProjectWizard", "Å", None, QtGui.QApplication.UnicodeUTF8))
        self.maskDiameterUnitComboBox.setItemText(1, QtGui.QApplication.translate("ProjectWizard", "Px", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleShapeComboBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Assists in setting the template disk size for template-matching", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleShapeComboBox.setItemText(0, QtGui.QApplication.translate("ProjectWizard", "Globular (e.g. 80S)", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleShapeComboBox.setItemText(1, QtGui.QApplication.translate("ProjectWizard", "Oblong (e.g. 40S)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("ProjectWizard", "Sample Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleDensityComboBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Assists in setting the overlap parameter for template-matching", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleDensityComboBox.setItemText(0, QtGui.QApplication.translate("ProjectWizard", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleDensityComboBox.setItemText(1, QtGui.QApplication.translate("ProjectWizard", "Sparse", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleDensityComboBox.setItemText(2, QtGui.QApplication.translate("ProjectWizard", "Dense", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleDensityInfoToolButton.setText(QtGui.QApplication.translate("ProjectWizard", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("ProjectWizard", "Sample Density", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ProjectWizard", "Parallel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("ProjectWizard", "Process Count", None, QtGui.QApplication.UnicodeUTF8))
        self.workerCountSpinBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Number of processes to run concurrently.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/information.png\" /> This uses more memory but is generally faster than increasing the thread count. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/mini/mini/exclamation.png\" /> The number of threads x the number of workers should not exceed the number of cores.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("ProjectWizard", "Thread Count", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("ProjectWizard", "Logging", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ProjectWizard", "Log to Console", None, QtGui.QApplication.UnicodeUTF8))
        self.enableStderrCheckBox.setToolTip(QtGui.QApplication.translate("ProjectWizard", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Log to the console (using the error stream)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is in addition to logging to the <span style=\" font-style:italic;\">project.log</span> file.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.fineTunePage.setTitle(QtGui.QApplication.translate("ProjectWizard", "Review Individual Program Options", None, QtGui.QApplication.UnicodeUTF8))
        self.workflowListView.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Select a program to view or change is current options", None, QtGui.QApplication.UnicodeUTF8))
        self.documentationURLToolButton.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Change the URL for the documentation", None, QtGui.QApplication.UnicodeUTF8))
        self.documentationURLToolButton.setText(QtGui.QApplication.translate("ProjectWizard", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsInformatToolButton.setToolTip(QtGui.QApplication.translate("ProjectWizard", "Information concerning the current page", None, QtGui.QApplication.UnicodeUTF8))

from ..icons import icons_rc;icons_rc;
