# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/robertlanglois/workspace/arachnida/src/arachnid/core/gui/pyui/ReferenceUI.ui'
#
# Created: Sat Dec  7 10:04:27 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from ..util.qt4_loader import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(396, 421)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.referenceTabWidget = QtGui.QTabWidget(Form)
        self.referenceTabWidget.setObjectName("referenceTabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setContentsMargins(3, 0, 3, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtGui.QWidget(self.tab)
        self.widget_3.setMinimumSize(QtCore.QSize(200, 200))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.referenceLineEdit = QtGui.QLineEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.referenceLineEdit.sizePolicy().hasHeightForWidth())
        self.referenceLineEdit.setSizePolicy(sizePolicy)
        self.referenceLineEdit.setObjectName("referenceLineEdit")
        self.gridLayout_3.addWidget(self.referenceLineEdit, 0, 0, 1, 1)
        self.referenceFilePushButton = QtGui.QPushButton(self.widget_3)
        self.referenceFilePushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mini/mini/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.referenceFilePushButton.setIcon(icon)
        self.referenceFilePushButton.setAutoDefault(False)
        self.referenceFilePushButton.setFlat(True)
        self.referenceFilePushButton.setObjectName("referenceFilePushButton")
        self.gridLayout_3.addWidget(self.referenceFilePushButton, 0, 1, 1, 1)
        self.widget_4 = QtGui.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtGui.QLabel(self.widget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.referenceDepthLabel = QtGui.QLabel(self.widget_4)
        self.referenceDepthLabel.setObjectName("referenceDepthLabel")
        self.gridLayout_4.addWidget(self.referenceDepthLabel, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.widget_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 0, 1, 1)
        self.referenceWidthLabel = QtGui.QLabel(self.widget_4)
        self.referenceWidthLabel.setObjectName("referenceWidthLabel")
        self.gridLayout_4.addWidget(self.referenceWidthLabel, 1, 1, 1, 1)
        self.referenceHeightLabel = QtGui.QLabel(self.widget_4)
        self.referenceHeightLabel.setObjectName("referenceHeightLabel")
        self.gridLayout_4.addWidget(self.referenceHeightLabel, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.widget_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 3, 0, 1, 1)
        self.referencePixelSizeDoubleSpinBox = QtGui.QDoubleSpinBox(self.widget_4)
        self.referencePixelSizeDoubleSpinBox.setDecimals(3)
        self.referencePixelSizeDoubleSpinBox.setObjectName("referencePixelSizeDoubleSpinBox")
        self.gridLayout_4.addWidget(self.referencePixelSizeDoubleSpinBox, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 4, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_3)
        self.referenceTabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setContentsMargins(3, 0, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.emdbCannedListView = QtGui.QListView(self.tab_2)
        self.emdbCannedListView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.emdbCannedListView.setViewMode(QtGui.QListView.IconMode)
        self.emdbCannedListView.setObjectName("emdbCannedListView")
        self.verticalLayout_6.addWidget(self.emdbCannedListView)
        self.widget_8 = QtGui.QWidget(self.tab_2)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.emdbNumberLineEdit = QtGui.QLineEdit(self.widget_8)
        self.emdbNumberLineEdit.setObjectName("emdbNumberLineEdit")
        self.horizontalLayout_3.addWidget(self.emdbNumberLineEdit)
        self.emdbDownloadPushButton = QtGui.QPushButton(self.widget_8)
        self.emdbDownloadPushButton.setAutoDefault(False)
        self.emdbDownloadPushButton.setObjectName("emdbDownloadPushButton")
        self.horizontalLayout_3.addWidget(self.emdbDownloadPushButton)
        self.verticalLayout_6.addWidget(self.widget_8)
        self.referenceTabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.referenceTabWidget)

        self.retranslateUi(Form)
        self.referenceTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceDepthLabel.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceWidthLabel.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceHeightLabel.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Reference Pixel Size", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceTabWidget.setTabText(self.referenceTabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Local File", None, QtGui.QApplication.UnicodeUTF8))
        self.emdbDownloadPushButton.setText(QtGui.QApplication.translate("Form", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceTabWidget.setTabText(self.referenceTabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "EMDB", None, QtGui.QApplication.UnicodeUTF8))

from ..icons import icons_rc;icons_rc;
