		SUBROUTINE FMRS_2(X,NSAM,NROW,INV)

        INTEGER, INTENT(INOUT) :: INV
        REAL, INTENT(INOUT) :: X(*)

        CALL FMRS(X,NSAM,NROW,1, 0.0D0, .TRUE.,.TRUE.,INV,IRTFLG)

        IF (IRTFLG .NE. 0) INV = 0

        END


