# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/robertlanglois/workspace/arachnida/src/arachnid/core/gui/dialogs/pyui/EmbeddingViewer.ui'
#
# Created: Sat Dec 22 17:45:07 2012
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(575, 552)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.centralHLayout = QtGui.QHBoxLayout()
        self.centralHLayout.setObjectName(_fromUtf8("centralHLayout"))
        self.dockWidget = QtGui.QDockWidget(self.centralwidget)
        self.dockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.dockWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setMargin(3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.xComboBox = QtGui.QComboBox(self.groupBox)
        self.xComboBox.setObjectName(_fromUtf8("xComboBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.xComboBox)
        self.yComboBox = QtGui.QComboBox(self.groupBox)
        self.yComboBox.setObjectName(_fromUtf8("yComboBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.yComboBox)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.colorComboBox = QtGui.QComboBox(self.groupBox)
        self.colorComboBox.setObjectName(_fromUtf8("colorComboBox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.colorComboBox)
        self.subsetComboBox = QtGui.QComboBox(self.groupBox)
        self.subsetComboBox.setObjectName(_fromUtf8("subsetComboBox"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.subsetComboBox)
        self.subsetListView = QtGui.QListView(self.groupBox)
        self.subsetListView.setObjectName(_fromUtf8("subsetListView"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.subsetListView)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.verticalLayout.addWidget(self.groupBox)
        self.imageGroupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.imageGroupBox.sizePolicy().hasHeightForWidth())
        self.imageGroupBox.setSizePolicy(sizePolicy)
        self.imageGroupBox.setObjectName(_fromUtf8("imageGroupBox"))
        self.formLayout_3 = QtGui.QFormLayout(self.imageGroupBox)
        self.formLayout_3.setMargin(3)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.imageGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.imageCountSpinBox = QtGui.QSpinBox(self.imageGroupBox)
        self.imageCountSpinBox.setObjectName(_fromUtf8("imageCountSpinBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.imageCountSpinBox)
        self.imageSepSpinBox = QtGui.QSpinBox(self.imageGroupBox)
        self.imageSepSpinBox.setMinimum(1)
        self.imageSepSpinBox.setMaximum(1000)
        self.imageSepSpinBox.setSingleStep(1)
        self.imageSepSpinBox.setProperty(_fromUtf8("value"), 40)
        self.imageSepSpinBox.setObjectName(_fromUtf8("imageSepSpinBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.imageSepSpinBox)
        self.imageZoomDoubleSpinBox = QtGui.QDoubleSpinBox(self.imageGroupBox)
        self.imageZoomDoubleSpinBox.setMinimum(0.0)
        self.imageZoomDoubleSpinBox.setMaximum(10.0)
        self.imageZoomDoubleSpinBox.setSingleStep(0.1)
        self.imageZoomDoubleSpinBox.setProperty(_fromUtf8("value"), 0.4)
        self.imageZoomDoubleSpinBox.setObjectName(_fromUtf8("imageZoomDoubleSpinBox"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.imageZoomDoubleSpinBox)
        self.averageCountSpinBox = QtGui.QSpinBox(self.imageGroupBox)
        self.averageCountSpinBox.setObjectName(_fromUtf8("averageCountSpinBox"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.averageCountSpinBox)
        self.label_4 = QtGui.QLabel(self.imageGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_8 = QtGui.QLabel(self.imageGroupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_5 = QtGui.QLabel(self.imageGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.keepSelectedCheckBox = QtGui.QCheckBox(self.imageGroupBox)
        self.keepSelectedCheckBox.setText(_fromUtf8(""))
        self.keepSelectedCheckBox.setObjectName(_fromUtf8("keepSelectedCheckBox"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.keepSelectedCheckBox)
        self.label_9 = QtGui.QLabel(self.imageGroupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.verticalLayout.addWidget(self.imageGroupBox)
        self.horizontalLayout.addWidget(self.widget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.centralHLayout.addWidget(self.dockWidget)
        self.horizontalLayout_2.addLayout(self.centralHLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionPan = QtGui.QAction(MainWindow)
        self.actionPan.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/arrow_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon1)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionHome = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/house.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon2)
        self.actionHome.setObjectName(_fromUtf8("actionHome"))
        self.actionZoom = QtGui.QAction(MainWindow)
        self.actionZoom.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/zoom_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon3)
        self.actionZoom.setObjectName(_fromUtf8("actionZoom"))
        self.actionForward = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/resultset_next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForward.setIcon(icon4)
        self.actionForward.setObjectName(_fromUtf8("actionForward"))
        self.actionBackward = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/resultset_previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBackward.setIcon(icon5)
        self.actionBackward.setObjectName(_fromUtf8("actionBackward"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon6)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionShow_Options = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/database_table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Options.setIcon(icon7)
        self.actionShow_Options.setObjectName(_fromUtf8("actionShow_Options"))
        self.actionHide_Controls = QtGui.QAction(MainWindow)
        self.actionHide_Controls.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/application_side_list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide_Controls.setIcon(icon8)
        self.actionHide_Controls.setObjectName(_fromUtf8("actionHide_Controls"))
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addAction(self.actionBackward)
        self.toolBar.addAction(self.actionForward)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addAction(self.actionZoom)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionShow_Options)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Plotting", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Subset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.imageGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Images", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Separation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Keep Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a file to plot or a stack of images to display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Meta+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPan.setText(QtGui.QApplication.translate("MainWindow", "pan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPan.setToolTip(QtGui.QApplication.translate("MainWindow", "Move the data in the plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setText(QtGui.QApplication.translate("MainWindow", "home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setToolTip(QtGui.QApplication.translate("MainWindow", "Reset the view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setText(QtGui.QApplication.translate("MainWindow", "zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setToolTip(QtGui.QApplication.translate("MainWindow", "Use the cursor to zoom in on an area of the plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForward.setText(QtGui.QApplication.translate("MainWindow", "forward", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForward.setToolTip(QtGui.QApplication.translate("MainWindow", "Step forward in action history", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackward.setText(QtGui.QApplication.translate("MainWindow", "backward", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackward.setToolTip(QtGui.QApplication.translate("MainWindow", "Step backward in action history", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Save the current plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Options.setText(QtGui.QApplication.translate("MainWindow", "Show Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Options.setToolTip(QtGui.QApplication.translate("MainWindow", "Display dialog to configure plot options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_Controls.setText(QtGui.QApplication.translate("MainWindow", "Hide Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_Controls.setToolTip(QtGui.QApplication.translate("MainWindow", "Hide the controls", None, QtGui.QApplication.UnicodeUTF8))

from arachnid.core.gui.icons import icons_rc
icons_rc;
