# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EmbeddingViewer.ui'
#
# Created: Sat Jul  6 20:44:19 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from arachnid.core.gui.util.qt4_loader import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(943, 624)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.centralHLayout = QtGui.QHBoxLayout()
        self.centralHLayout.setObjectName("centralHLayout")
        self.dockWidget = QtGui.QDockWidget(self.centralwidget)
        self.dockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtGui.QToolBox(self.dockWidgetContents)
        self.toolBox.setObjectName("toolBox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 941, 407))
        self.page.setObjectName("page")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setContentsMargins(3, 3, 3, 3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.xComboBox = QtGui.QComboBox(self.groupBox)
        self.xComboBox.setObjectName("xComboBox")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.xComboBox)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.yComboBox = QtGui.QComboBox(self.groupBox)
        self.yComboBox.setObjectName("yComboBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.yComboBox)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.colorComboBox = QtGui.QComboBox(self.groupBox)
        self.colorComboBox.setObjectName("colorComboBox")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.colorComboBox)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.subsetComboBox = QtGui.QComboBox(self.groupBox)
        self.subsetComboBox.setObjectName("subsetComboBox")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.subsetComboBox)
        self.widget = QtGui.QWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.updatePushButton = QtGui.QPushButton(self.widget)
        self.updatePushButton.setObjectName("updatePushButton")
        self.gridLayout.addWidget(self.updatePushButton, 0, 0, 1, 1)
        self.selectAllPushButton = QtGui.QPushButton(self.widget)
        self.selectAllPushButton.setObjectName("selectAllPushButton")
        self.gridLayout.addWidget(self.selectAllPushButton, 1, 0, 1, 1)
        self.unselectAllPushButton = QtGui.QPushButton(self.widget)
        self.unselectAllPushButton.setObjectName("unselectAllPushButton")
        self.gridLayout.addWidget(self.unselectAllPushButton, 2, 0, 1, 1)
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.widget)
        self.subsetListView = QtGui.QListView(self.groupBox)
        self.subsetListView.setObjectName("subsetListView")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.subsetListView)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.toolBox.addItem(self.page, "")
        self.imageGroupBox = QtGui.QWidget()
        self.imageGroupBox.setGeometry(QtCore.QRect(0, 0, 941, 407))
        self.imageGroupBox.setObjectName("imageGroupBox")
        self.formLayout = QtGui.QFormLayout(self.imageGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.imageGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.imageCountSpinBox = QtGui.QSpinBox(self.imageGroupBox)
        self.imageCountSpinBox.setObjectName("imageCountSpinBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.imageCountSpinBox)
        self.label_5 = QtGui.QLabel(self.imageGroupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.imageSepSpinBox = QtGui.QSpinBox(self.imageGroupBox)
        self.imageSepSpinBox.setMinimum(1)
        self.imageSepSpinBox.setMaximum(1000)
        self.imageSepSpinBox.setSingleStep(1)
        self.imageSepSpinBox.setProperty("value", 40)
        self.imageSepSpinBox.setObjectName("imageSepSpinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.imageSepSpinBox)
        self.label_8 = QtGui.QLabel(self.imageGroupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.imageZoomDoubleSpinBox = QtGui.QDoubleSpinBox(self.imageGroupBox)
        self.imageZoomDoubleSpinBox.setMinimum(0.0)
        self.imageZoomDoubleSpinBox.setMaximum(10.0)
        self.imageZoomDoubleSpinBox.setSingleStep(0.1)
        self.imageZoomDoubleSpinBox.setProperty("value", 0.4)
        self.imageZoomDoubleSpinBox.setObjectName("imageZoomDoubleSpinBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.imageZoomDoubleSpinBox)
        self.label_4 = QtGui.QLabel(self.imageGroupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.averageCountSpinBox = QtGui.QSpinBox(self.imageGroupBox)
        self.averageCountSpinBox.setObjectName("averageCountSpinBox")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.averageCountSpinBox)
        self.label_9 = QtGui.QLabel(self.imageGroupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.keepSelectedCheckBox = QtGui.QCheckBox(self.imageGroupBox)
        self.keepSelectedCheckBox.setText("")
        self.keepSelectedCheckBox.setObjectName("keepSelectedCheckBox")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.keepSelectedCheckBox)
        self.selectGroupComboBox = QtGui.QComboBox(self.imageGroupBox)
        self.selectGroupComboBox.setObjectName("selectGroupComboBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.selectGroupComboBox)
        self.label_11 = QtGui.QLabel(self.imageGroupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_11)
        self.toolBox.addItem(self.imageGroupBox, "")
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 941, 407))
        self.page_3.setObjectName("page_3")
        self.formLayout_3 = QtGui.QFormLayout(self.page_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtGui.QLabel(self.page_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.dpiSpinBox = QtGui.QSpinBox(self.page_3)
        self.dpiSpinBox.setMinimum(72)
        self.dpiSpinBox.setMaximum(10000)
        self.dpiSpinBox.setProperty("value", 100)
        self.dpiSpinBox.setObjectName("dpiSpinBox")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.dpiSpinBox)
        self.toolBox.addItem(self.page_3, "")
        self.horizontalLayout.addWidget(self.toolBox)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.centralHLayout.addWidget(self.dockWidget)
        self.horizontalLayout_2.addLayout(self.centralHLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 943, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mini/mini/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPan = QtGui.QAction(MainWindow)
        self.actionPan.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/mini/mini/arrow_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon1)
        self.actionPan.setObjectName("actionPan")
        self.actionHome = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/mini/mini/house.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon2)
        self.actionHome.setObjectName("actionHome")
        self.actionZoom = QtGui.QAction(MainWindow)
        self.actionZoom.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/mini/mini/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon3)
        self.actionZoom.setObjectName("actionZoom")
        self.actionForward = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/mini/mini/resultset_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForward.setIcon(icon4)
        self.actionForward.setObjectName("actionForward")
        self.actionBackward = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/mini/mini/resultset_previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBackward.setIcon(icon5)
        self.actionBackward.setObjectName("actionBackward")
        self.actionSave = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/mini/mini/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon6)
        self.actionSave.setObjectName("actionSave")
        self.actionShow_Options = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/mini/mini/database_table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Options.setIcon(icon7)
        self.actionShow_Options.setObjectName("actionShow_Options")
        self.actionHide_Controls = QtGui.QAction(MainWindow)
        self.actionHide_Controls.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/mini/mini/application_side_list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide_Controls.setIcon(icon8)
        self.actionHide_Controls.setObjectName("actionHide_Controls")
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addAction(self.actionBackward)
        self.toolBar.addAction(self.actionForward)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addAction(self.actionZoom)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionShow_Options)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Subset", None, QtGui.QApplication.UnicodeUTF8))
        self.updatePushButton.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllPushButton.setText(QtGui.QApplication.translate("MainWindow", "SelectAll", None, QtGui.QApplication.UnicodeUTF8))
        self.unselectAllPushButton.setText(QtGui.QApplication.translate("MainWindow", "UnselectAll", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("MainWindow", "Plotting", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Separation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Average", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Keep Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Highlight Group", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.imageGroupBox), QtGui.QApplication.translate("MainWindow", "Image Markers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Dots Per Inch", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a file to plot or a stack of images to display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Meta+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPan.setText(QtGui.QApplication.translate("MainWindow", "pan", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPan.setToolTip(QtGui.QApplication.translate("MainWindow", "Move the data in the plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setText(QtGui.QApplication.translate("MainWindow", "home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setToolTip(QtGui.QApplication.translate("MainWindow", "Reset the view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setText(QtGui.QApplication.translate("MainWindow", "zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setToolTip(QtGui.QApplication.translate("MainWindow", "Use the cursor to zoom in on an area of the plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForward.setText(QtGui.QApplication.translate("MainWindow", "forward", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForward.setToolTip(QtGui.QApplication.translate("MainWindow", "Step forward in action history", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackward.setText(QtGui.QApplication.translate("MainWindow", "backward", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackward.setToolTip(QtGui.QApplication.translate("MainWindow", "Step backward in action history", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Save the current plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Options.setText(QtGui.QApplication.translate("MainWindow", "Show Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Options.setToolTip(QtGui.QApplication.translate("MainWindow", "Display dialog to configure plot options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_Controls.setText(QtGui.QApplication.translate("MainWindow", "Hide Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_Controls.setToolTip(QtGui.QApplication.translate("MainWindow", "Hide the controls", None, QtGui.QApplication.UnicodeUTF8))

from arachnid.core.gui.icons import icons_rc
icons_rc;
