# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/robertlanglois/workspace/arachnida/src/arachnid/core/gui/dialogs/pyui/MontageViewer.ui'
#
# Created: Sat Apr  6 15:21:52 2013
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(695, 551)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.centralHLayout = QtGui.QHBoxLayout()
        self.centralHLayout.setObjectName(_fromUtf8("centralHLayout"))
        self.dockWidget = QtGui.QDockWidget(self.centralwidget)
        self.dockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget = QtGui.QWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.widget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setContentsMargins(0, 0, 0, -1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.imageZoomDoubleSpinBox = QtGui.QDoubleSpinBox(self.tab)
        self.imageZoomDoubleSpinBox.setMinimum(0.01)
        self.imageZoomDoubleSpinBox.setMaximum(1.0)
        self.imageZoomDoubleSpinBox.setSingleStep(0.1)
        self.imageZoomDoubleSpinBox.setProperty(_fromUtf8("value"), 1.0)
        self.imageZoomDoubleSpinBox.setObjectName(_fromUtf8("imageZoomDoubleSpinBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.imageZoomDoubleSpinBox)
        self.zoomSlider = QtGui.QSlider(self.tab)
        self.zoomSlider.setMinimum(1)
        self.zoomSlider.setMaximum(100)
        self.zoomSlider.setProperty(_fromUtf8("value"), 100)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.zoomSlider.setObjectName(_fromUtf8("zoomSlider"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.zoomSlider)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.contrastSlider = QtGui.QSlider(self.tab)
        self.contrastSlider.setMinimum(1)
        self.contrastSlider.setMaximum(400)
        self.contrastSlider.setPageStep(40)
        self.contrastSlider.setProperty(_fromUtf8("value"), 200)
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.contrastSlider.setObjectName(_fromUtf8("contrastSlider"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.contrastSlider)
        self.pageSpinBox = QtGui.QSpinBox(self.tab)
        self.pageSpinBox.setMaximum(99999)
        self.pageSpinBox.setObjectName(_fromUtf8("pageSpinBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pageSpinBox)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.tab_2)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.imageCountSpinBox = QtGui.QSpinBox(self.tab_2)
        self.imageCountSpinBox.setFrame(True)
        self.imageCountSpinBox.setMinimum(1)
        self.imageCountSpinBox.setMaximum(9999999)
        self.imageCountSpinBox.setProperty(_fromUtf8("value"), 10)
        self.imageCountSpinBox.setObjectName(_fromUtf8("imageCountSpinBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.imageCountSpinBox)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.decimateSpinBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.decimateSpinBox.setMinimum(1.0)
        self.decimateSpinBox.setMaximum(16.0)
        self.decimateSpinBox.setObjectName(_fromUtf8("decimateSpinBox"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.decimateSpinBox)
        self.loadImagesPushButton = QtGui.QPushButton(self.tab_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/arrow_rotate_clockwise.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadImagesPushButton.setIcon(icon)
        self.loadImagesPushButton.setObjectName(_fromUtf8("loadImagesPushButton"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.loadImagesPushButton)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.clampDoubleSpinBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.clampDoubleSpinBox.setMinimum(1.0)
        self.clampDoubleSpinBox.setSingleStep(1.0)
        self.clampDoubleSpinBox.setProperty(_fromUtf8("value"), 5.0)
        self.clampDoubleSpinBox.setObjectName(_fromUtf8("clampDoubleSpinBox"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.clampDoubleSpinBox)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.formLayout_4 = QtGui.QFormLayout(self.tab_3)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.selectAllButton = QtGui.QPushButton(self.tab_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/exclamation.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectAllButton.setIcon(icon1)
        self.selectAllButton.setObjectName(_fromUtf8("selectAllButton"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.selectAllButton)
        self.unselectAllButton = QtGui.QPushButton(self.tab_3)
        self.unselectAllButton.setIcon(icon1)
        self.unselectAllButton.setObjectName(_fromUtf8("unselectAllButton"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.unselectAllButton)
        self.deleteModelButton = QtGui.QPushButton(self.tab_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/error.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteModelButton.setIcon(icon2)
        self.deleteModelButton.setObjectName(_fromUtf8("deleteModelButton"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.deleteModelButton)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setMargin(3)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.imageFileComboBox = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageFileComboBox.sizePolicy().hasHeightForWidth())
        self.imageFileComboBox.setSizePolicy(sizePolicy)
        self.imageFileComboBox.setObjectName(_fromUtf8("imageFileComboBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.imageFileComboBox)
        self.fileTableView = QtGui.QTableView(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fileTableView.sizePolicy().hasHeightForWidth())
        self.fileTableView.setSizePolicy(sizePolicy)
        self.fileTableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.fileTableView.setProperty(_fromUtf8("showDropIndicator"), False)
        self.fileTableView.setObjectName(_fromUtf8("fileTableView"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.fileTableView)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.widget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.centralHLayout.addWidget(self.dockWidget)
        self.imageListView = QtGui.QListView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageListView.sizePolicy().hasHeightForWidth())
        self.imageListView.setSizePolicy(sizePolicy)
        self.imageListView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.imageListView.setProperty(_fromUtf8("showDropIndicator"), False)
        self.imageListView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.imageListView.setMovement(QtGui.QListView.Static)
        self.imageListView.setProperty(_fromUtf8("isWrapping"), True)
        self.imageListView.setSpacing(2)
        self.imageListView.setViewMode(QtGui.QListView.IconMode)
        self.imageListView.setObjectName(_fromUtf8("imageListView"))
        self.centralHLayout.addWidget(self.imageListView)
        self.horizontalLayout_2.addLayout(self.centralHLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 695, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon3)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionFitToView = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/arrow_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFitToView.setIcon(icon4)
        self.actionFitToView.setObjectName(_fromUtf8("actionFitToView"))
        self.actionHome = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/house.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHome.setIcon(icon5)
        self.actionHome.setObjectName(_fromUtf8("actionHome"))
        self.actionZoom = QtGui.QAction(MainWindow)
        self.actionZoom.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/zoom_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom.setIcon(icon6)
        self.actionZoom.setObjectName(_fromUtf8("actionZoom"))
        self.actionForward = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/resultset_next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionForward.setIcon(icon7)
        self.actionForward.setObjectName(_fromUtf8("actionForward"))
        self.actionBackward = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/resultset_previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBackward.setIcon(icon8)
        self.actionBackward.setObjectName(_fromUtf8("actionBackward"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon9)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionShow_Options = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/database_table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_Options.setIcon(icon10)
        self.actionShow_Options.setObjectName(_fromUtf8("actionShow_Options"))
        self.actionHide_Controls = QtGui.QAction(MainWindow)
        self.actionHide_Controls.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/application_side_list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHide_Controls.setIcon(icon11)
        self.actionHide_Controls.setObjectName(_fromUtf8("actionHide_Controls"))
        self.actionOriginal_Size = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/arrow_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOriginal_Size.setIcon(icon12)
        self.actionOriginal_Size.setObjectName(_fromUtf8("actionOriginal_Size"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/mini/mini/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon13)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBackward)
        self.toolBar.addAction(self.actionForward)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.pageSpinBox.setSuffix(QtGui.QApplication.translate("MainWindow", " of 0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Count", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Decimate", None, QtGui.QApplication.UnicodeUTF8))
        self.loadImagesPushButton.setText(QtGui.QApplication.translate("MainWindow", "Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Clamp", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllButton.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.unselectAllButton.setText(QtGui.QApplication.translate("MainWindow", "Unselect All", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteModelButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Delete all columns except first three and all files except selected", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteModelButton.setText(QtGui.QApplication.translate("MainWindow", "Delete Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a file to plot or a stack of images to display", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Meta+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitToView.setText(QtGui.QApplication.translate("MainWindow", "Fit to View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFitToView.setToolTip(QtGui.QApplication.translate("MainWindow", "Fit all images to view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setText(QtGui.QApplication.translate("MainWindow", "home", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHome.setToolTip(QtGui.QApplication.translate("MainWindow", "Reset the view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setText(QtGui.QApplication.translate("MainWindow", "zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setToolTip(QtGui.QApplication.translate("MainWindow", "Use the cursor to zoom in on an area of the plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForward.setText(QtGui.QApplication.translate("MainWindow", "forward", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForward.setToolTip(QtGui.QApplication.translate("MainWindow", "Step forward in action history", None, QtGui.QApplication.UnicodeUTF8))
        self.actionForward.setShortcut(QtGui.QApplication.translate("MainWindow", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackward.setText(QtGui.QApplication.translate("MainWindow", "backward", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackward.setToolTip(QtGui.QApplication.translate("MainWindow", "Step backward in action history", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBackward.setShortcut(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Save the current plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Options.setText(QtGui.QApplication.translate("MainWindow", "Show Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Options.setToolTip(QtGui.QApplication.translate("MainWindow", "Display dialog to configure plot options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_Controls.setText(QtGui.QApplication.translate("MainWindow", "Hide Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide_Controls.setToolTip(QtGui.QApplication.translate("MainWindow", "Hide the controls", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOriginal_Size.setText(QtGui.QApplication.translate("MainWindow", "Original Size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOriginal_Size.setToolTip(QtGui.QApplication.translate("MainWindow", "Zoom images to original size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setToolTip(QtGui.QApplication.translate("MainWindow", "Display help dialog", None, QtGui.QApplication.UnicodeUTF8))

from arachnid.core.gui.icons import icons_rc
icons_rc;
